# Auto-generated by StrataWave
# 1D SH-like u-p column assembly for PM4Sand/PM4Silt calibration-ready workflows
wipe
model BasicBuilder -ndm 2 -ndf 3
set motion_file "motion_processed.csv"
set output_dir "."
file mkdir $output_dir
set dt 0.00500000
set colWidth 1.00000000
set thickness 1.00000000
set g 9.81000000
set fBulk 2200000.00000000
set fMass 1.00000000
set hPermInput 0.00001000
set vPermInput 0.00001000
# Convert hydraulic conductivity (m/s) to quadUP permeability coefficient
set permDen [expr {$g * $fMass}]
if {$permDen <= 0.0} { set permDen 9.81 }
set hPerm [expr {$hPermInput / $permDen}]
set vPerm [expr {$vPermInput / $permDen}]
# Use high permeability during gravity to avoid locked pore-pressure transients
set hPermGrav 1.0
set vPermGrav 1.0
set sigmaVRef 151.20000000
set nLayers 2
set nElemY 18
set nNodeY [expr {$nElemY + 1}]
set dzList {0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 1.11111111 1.11111111 1.11111111 1.11111111 1.11111111 1.11111111 1.11111111 1.11111111 1.11111111}
set matByElem {1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2}
set pm4MatTags {}

# Material definitions
# Layer 1 Elastic fallback material
nDMaterial ElasticIsotropic 1 149347.604485 0.300000 1.87563710
# Layer 2 Elastic fallback material
nDMaterial ElasticIsotropic 2 427958.409786 0.300000 1.95718654

# Node assembly (2-node wide column for 1D emulation)
set y 0.0
set nodeL(1) 1001
set nodeR(1) 2001
node $nodeL(1) 0.0 $y
node $nodeR(1) $colWidth $y
for {set i 2} {$i <= $nNodeY} {incr i} {
    set dz [lindex $dzList [expr {$i - 2}]]
    set y [expr {$y - $dz}]
    set nodeL($i) [expr {1000 + $i}]
    set nodeR($i) [expr {2000 + $i}]
    node $nodeL($i) 0.0 $y
    node $nodeR($i) $colWidth $y
}

# Boundary conditions and 1D constraints
for {set i 1} {$i <= $nNodeY} {incr i} {
    equalDOF $nodeL($i) $nodeR($i) 1
}
for {set i 2} {$i < $nNodeY} {incr i} {
    fix $nodeL($i) 0 1 0
    fix $nodeR($i) 0 1 0
}
# Drained top boundary
fix $nodeL(1) 0 1 1
fix $nodeR(1) 0 1 1
# Base boundary: elastic half-space (Lysmer dashpot in DOF-1)
fix $nodeL($nNodeY) 0 1 1
fix $nodeR($nNodeY) 0 1 1
set dashL 900001
set dashR 900002
node $dashL 0.0 $y
node $dashR $colWidth $y
fix $dashL 1 1 1
fix $dashR 1 1 1
set baseRho 1.95718654
set baseVs 290.00000000
set dashpotC [expr {$baseRho * $baseVs * $colWidth * $thickness}]
uniaxialMaterial Viscous 9001 $dashpotC 1.0
element zeroLength 9001 $nodeL($nNodeY) $dashL -mat 9001 -dir 1
element zeroLength 9002 $nodeR($nNodeY) $dashR -mat 9001 -dir 1

# u-p elements
set eleTag 1
for {set e 1} {$e <= $nElemY} {incr e} {
    set n1 $nodeL($e)
    set n2 $nodeL([expr {$e + 1}])
    set n3 $nodeR([expr {$e + 1}])
    set n4 $nodeR($e)
    set matTag [lindex $matByElem [expr {$e - 1}]]
    element quadUP $eleTag $n1 $n2 $n3 $n4 $thickness $matTag $fBulk $fMass $hPermGrav $vPermGrav 0.0 -$g
    incr eleTag
}
# Permeability parameter tags for post-gravity update
set hPermParamTags {}
set vPermParamTags {}
set pTag 1
for {set e 1} {$e <= $nElemY} {incr e} {
    parameter $pTag element $e hPerm
    lappend hPermParamTags $pTag
    incr pTag
    parameter $pTag element $e vPerm
    lappend vPermParamTags $pTag
    incr pTag
}

# Gravity stage
updateMaterialStage -material 1 -stage 0
updateMaterialStage -material 2 -stage 0
constraints Penalty 1.0e16 1.0e16
numberer RCM
system BandGeneral
test NormDispIncr 1.0e-6 50 0
algorithm Newton
integrator Newmark 0.6 0.3025
analysis Transient
set okG [analyze 20 $dt]
if {$okG != 0} {
    algorithm ModifiedNewton
    test NormDispIncr 1.0e-5 80 0
    set okG [analyze 40 [expr {$dt / 2.0}]]
}
if {$okG != 0} {
    puts "Gravity stage did not converge."
    exit $okG
}
loadConst -time 0.0
# Restore user-defined permeability for dynamic stage
foreach pTag $hPermParamTags {
    updateParameter $pTag $hPerm
}
foreach pTag $vPermParamTags {
    updateParameter $pTag $vPerm
}

# Dynamic stage
updateMaterialStage -material 1 -stage 1
updateMaterialStage -material 2 -stage 1
# PM4 requires FirstCall initialization after stage switch when defaults are stress-dependent
for {set e 1} {$e <= $nElemY} {incr e} {
    set matTag [lindex $matByElem [expr {$e - 1}]]
    if {[lsearch -exact $pm4MatTags $matTag] >= 0} {
        setParameter -value 0 -ele $e FirstCall $matTag
    }
}
timeSeries Path 1 -dt $dt -filePath $motion_file -factor 1.0
pattern UniformExcitation 1 1 -accel 1
recorder Node -file "$output_dir/surface_acc.out" -time -node $nodeL(1) -dof 1 accel
set pwpNode $nodeL([expr {int(($nNodeY + 1) / 2)}])
recorder Node -file "$output_dir/pwp_raw.out" -time -node $pwpNode -dof 3 disp
# Layer representative stress/strain recorders for hysteresis UI channels
array unset layerRepElem
for {set e 1} {$e <= $nElemY} {incr e} {
    set matTag [lindex $matByElem [expr {$e - 1}]]
    if {![info exists layerRepElem($matTag)]} {
        set layerRepElem($matTag) $e
    }
}
foreach matTag [lsort -integer [array names layerRepElem]] {
    set repEle $layerRepElem($matTag)
    set stressFile [format "%s/layer_%s_stress.out" $output_dir $matTag]
    set strainFile [format "%s/layer_%s_strain.out" $output_dir $matTag]
    set pwpFile [format "%s/layer_%s_pwp_raw.out" $output_dir $matTag]
    catch {
        recorder Element -file $stressFile -time -ele $repEle material 1 stress
    }
    catch {
        recorder Element -file $strainFile -time -ele $repEle material 1 strain
    }
    catch {
        recorder Node -file $pwpFile -time -node $nodeL([expr {$repEle + 1}]) -dof 3 disp
    }
}
set in [open $motion_file r]
set raw [split [string trim [read $in]] "\n"]
close $in
set nSteps [llength $raw]
if {$nSteps < 2} { set nSteps 2 }
constraints Penalty 1.0e16 1.0e16
numberer RCM
system BandGeneral
test NormDispIncr 1.0e-5 50 0
algorithm KrylovNewton
integrator Newmark 0.6 0.3025
analysis Transient
set ok 0
for {set i 1} {$i <= $nSteps} {incr i} {
    set ok [analyze 1 $dt]
    if {$ok != 0} {
        algorithm ModifiedNewton
        test NormDispIncr 1.0e-5 80 0
        set ok [analyze 2 [expr {$dt / 2.0}]]
        algorithm KrylovNewton
        test NormDispIncr 1.0e-5 50 0
    }
    if {$ok != 0} { break }
}
if {$ok != 0} {
    puts "Dynamic analysis failed after fallback attempt."
}

# Convert pore-pressure record to approximate ru ratio
if {[file exists "$output_dir/pwp_raw.out"]} {
    set fin [open "$output_dir/pwp_raw.out" r]
    set fout [open "$output_dir/pwp_ru.out" w]
    while {[gets $fin line] >= 0} {
        set v [string trim $line]
        if {$v eq ""} { continue }
        set t 0.0
        set pwp 0.0
        scan $v "%f %f" t pwp
        # OpenSees geomechanics sign convention may report compression as negative.
        set ru [expr {-$pwp / $sigmaVRef}]
        if {$ru < 0.0} { set ru 0.0 }
        if {$ru > 1.5} { set ru 1.5 }
        puts $fout "$t $ru"
    }
    close $fin
    close $fout
} else {
    set fout [open "$output_dir/pwp_ru.out" w]
    puts $fout "0.0 0.0"
    puts $fout "$dt 0.0"
    close $fout
}
if {![file exists "$output_dir/surface_acc.out"]} {
    set fout [open "$output_dir/surface_acc.out" w]
    puts $fout "0.0"
    puts $fout "0.0"
    close $fout
}
puts "OpenSees run complete"
exit $ok
